#!/usr/bin/env bash
#
# deploy-docker.sh — run a stress-strike fleet (master + N workers) with
# Docker, interactively. Ordinary-user friendly: answer a few questions,
# everything else is automatic.
#
# Usage:
#   ./scripts/deploy-docker.sh                # interactive wizard
#   ./scripts/deploy-docker.sh -y URL=http://example.com USERS=20 DURATION=30 WORKERS=2 TOKEN=secret
#   ./scripts/deploy-docker.sh down           # stop + remove the fleet
#   ./scripts/deploy-docker.sh logs           # tail the fleet logs
#
# Key=value pairs (or -y defaults): URL, USERS, DURATION, WORKERS, TOKEN,
# METHOD. TOKEN empty disables auth (not recommended).

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=deploy/fleet/common.sh
source "${REPO_ROOT}/deploy/fleet/common.sh"

URL="${URL:-}"
USERS="${USERS:-20}"
DURATION="${DURATION:-30}"
WORKERS="${WORKERS:-2}"
TOKEN="${TOKEN:-}"
METHOD="${METHOD:-GET}"
ASSUME_YES=0
CMD="up"

# --- parse args: 'down'/'logs' + -y + KEY=VALUE --------------------------------
for a in "$@"; do
  case "$a" in
    down) CMD="down" ;;
    logs) CMD="logs" ;;
    generate) CMD="generate" ;;
    -y) ASSUME_YES=1 ;;
    *=*) export "$a" ;;
    *) AS_EXTRA+=("$a") ;;
  esac
done

require_cmd docker "install Docker Desktop from https://www.docker.com/products/docker-desktop/"

COMPOSE_FILE="${REPO_ROOT}/dist/docker-compose.generated.yml"

if [[ "$CMD" == "down" ]]; then
  require_cmd docker compose "Docker Desktop includes 'docker compose'"
  [[ -f "$COMPOSE_FILE" ]] || { log_info "no generated fleet to stop (file not found)"; exit 0; }
  docker compose -f "$COMPOSE_FILE" down
  log_ok "fleet stopped (containers removed)"
  exit 0
fi
if [[ "$CMD" == "logs" ]]; then
  require_cmd docker compose "Docker Desktop includes 'docker compose'"
  [[ -f "$COMPOSE_FILE" ]] || { log_err "no generated fleet (file not found)"; exit 1; }
  exec docker compose -f "$COMPOSE_FILE" logs -f --tail=50
fi

# --- wizard ----------------------------------------------------------------------
banner "stress-strike Docker fleet"
if [[ "$CMD" != "generate" ]]; then
  log_step "checking docker..."
  docker info >/dev/null 2>&1 || { log_err "docker daemon not running. Start Docker Desktop first."; exit 1; }
  if ! docker compose version >/dev/null 2>&1; then
    log_warn "'docker compose' plugin not found; trying legacy 'docker-compose'"
    command -v docker-compose >/dev/null 2>&1 || { log_err "need the compose plugin (Docker Desktop >= 4.18 bundles it)"; exit 1; }
  fi
fi

ask() { if [[ $ASSUME_YES -eq 1 ]]; then return 0; else prompt_var "$1" "$2" "${3:-}"; fi; }

[[ $ASSUME_YES -eq 1 ]] && URL="${URL:-http://example.com}"
if [[ -z "$URL" ]]; then
  while [[ -z "$URL" ]]; do
    prompt_var URL "target URL to load after the fleet is up" "http://example.com"
  done
fi
ask WORKERS "number of workers (1-20)" "${WORKERS}"
[[ "$WORKERS" =~ ^[0-9]+$ ]] && [[ "$WORKERS" -ge 1 ]] && [[ "$WORKERS" -le 20 ]] || { log_err "WORKERS must be 1..20"; exit 1; }
ask USERS   "virtual users"      "${USERS}"
ask DURATION "duration (seconds)" "${DURATION}"
[[ -z "$TOKEN" ]] && {
  if [[ $ASSUME_YES -eq 1 ]]; then
    : # leave empty in -y mode (warned below)
  else
    y="y"
    prompt_yes_no y "protect the control plane with a shared token?" "y"
    [[ "$y" == "y" ]] && prompt_var TOKEN "token (any secret string)" ""
  fi
}
[[ -z "$TOKEN" ]] && log_warn "running WITHOUT a control-plane token"

if [[ "$CMD" != "generate" ]]; then
  confirm "build the images and start the fleet? (first build can take a few minutes)" "y"
fi

# --- generate compose --------------------------------------------------------------
mkdir -p "$(dirname "$COMPOSE_FILE")"
{
  cat <<EOF
# generated by scripts/deploy-docker.sh — regenerate instead of editing
services:
  master:
    build:
      context: ${REPO_ROOT}
      dockerfile: Dockerfile.master
    command:
      - /usr/local/bin/stress-strike-master
      - -listen
      - 0.0.0.0:50051
      - -url
      - ${URL}
      - -method
      - ${METHOD}
      - -users
      - "${USERS}"
      - -duration
      - "${DURATION}"
      - -wait-workers
      - "${WORKERS}"
      - -wait-timeout
      - "60"
EOF
  [[ -z "$TOKEN" ]] || cat <<EOF
      - -token
      - ${TOKEN}
EOF
  cat <<EOF
    ports:
      - "50051:50051"
    networks: [strike]
    restart: unless-stopped
EOF
  for i in $(seq 1 "$WORKERS"); do
    cat <<EOF

  worker-${i}:
    build:
      context: ${REPO_ROOT}
      dockerfile: Dockerfile.worker
    command:
      - /usr/local/bin/stress-strike-worker
      - -listen
      - 0.0.0.0:50061
      - -id
      - docker-worker-${i}
      - -advertise
      - "worker-${i}:50061"
      - -master
      - "master:50051"
      - -token
      - ${TOKEN}
    ulimits:
      nofile: { soft: 1048576, hard: 1048576 }
    networks: [strike]
    restart: unless-stopped
EOF
  done
  cat <<'EOF'

networks:
  strike: {}
EOF
} > "$COMPOSE_FILE"
log_ok "compose file written: ${COMPOSE_FILE}"

if [[ "$CMD" == "generate" ]]; then
  log_ok "generate mode — no containers started. Run '$0' to really deploy."
  exit 0
fi

docker compose -f "$COMPOSE_FILE" up -d --build
log_ok "fleet is up!"

echo
banner "fleet is running"
echo "  master (gRPC):  http://localhost:50051   (control plane)"
echo "  workers:        ${WORKERS}"
echo "  target:         ${URL}  (users=${USERS}, duration=${DURATION}s)"
echo
echo "  watch the run:  $0 logs"
echo "  stop the fleet: $0 down"
echo "  rerun (new URL etc. change settings): $0 -y URL=... DURATION=... down && $0"